# Site settings
title: Daisydan
header-img: "http://7xnl4q.com1.z0.glb.clouddn.com/home-bg.jpg"
email: daisyzhou.me@gmail.com
description: 前端开发工程师一枚！
baseurl: ""
url: "https://dandanzhou.github.io"


# SNS settings
RSS: true
github_username:    dandanzhou



# Build settings
highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM        # use Github Flavored Markdown !important


# Sidebar settings
sidebar: true
sidebar-featured-tags: true
sidebar-about-description: "靠自己才是王道！"
sidebar-avatar: "http://7xnl4q.com1.z0.glb.clouddn.com/avatar-zdd.jpeg"     # use absolute URL.

# Friends
friends: [
    {
        title: veryyoung,
        href: "http://veryyoung.me"
    },{
        title: HuanHuan,
        href: "http://minishine.github.io"
    },{
        title: COCO,
        href: "http://stayhungry.me"
    }
]
